[theme]
primaryColor = "#ffffff"  # White (for buttons, links)
backgroundColor = "#008080"  # Teal (Main background)
secondaryBackgroundColor = "#f0f8ff"  # Light teal/white (for sidebar, chat bubbles)
textColor = "#ffffff"  # White text for contrast
font = "sans serif"
